// Load .env only in development
if (process.env.NODE_ENV !== "production") {
  require("dotenv").config();
}

const express = require("express");
const mongoose = require("mongoose");
const axios = require("axios");
const cors = require("cors");
const { body, validationResult } = require("express-validator");
const { analyzeWithLLM } = require("./llm");
const Scan = require("./models/scan");

const app = express();
app.use(express.json());

// ✅ CORS setup
app.use(
  cors({
    origin: ["http://localhost:5713", "https://webshield.vercel.app"],
    methods: ["GET", "POST", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization"],
  })
);

// Standard OPTIONS handler
app.options("*", cors());

// Connect to MongoDB
mongoose
  .connect(process.env.MONGODB_URI)
  .then(() => console.log("✅ MongoDB connected"))
  .catch((err) => console.error("❌ MongoDB connection error:", err));

// Health check
app.get("/", (req, res) => res.send("🌐 WebShield backend is running!"));

// Whitelist for known safe domains
const whitelist = [
  "google.com",
  "github.com",
  "mozilla.org",
  "example.com",
  "spotify.com",
  "wikipedia.org",
  "microsoft.com",
  "amazon.com",
];

// Helper to check whitelist
function isWhitelisted(finalUrl) {
  if (!finalUrl) return false;
  const norm = finalUrl.toLowerCase();
  return whitelist.some((d) => norm.includes(d));
}

// Deterministic phishing detection
function detectPhishing(inputUrl) {
  const reasons = [];
  let urlObj;

  try {
    urlObj = new URL(inputUrl);
  } catch {
    return { flagged: true, reasons: ["Invalid URL format"] };
  }

  const hostname = urlObj.hostname.toLowerCase();
  const pathname = urlObj.pathname.toLowerCase();
  const search = urlObj.search.toLowerCase();
  const protocol = urlObj.protocol.toLowerCase();

  // 1) HTTPS check
  if (protocol !== "https:") reasons.push("Uses HTTP or missing HTTPS");

  // 2) Suspicious keywords
  const suspiciousPatterns = [
    "login", "signin", "verify", "update", "account", "secure", "bank",
    "confirm", "ebaylogin", "paypal", "password", "token", "auth", "session",
    "verify-account",
  ];
  if (suspiciousPatterns.some(p => hostname.includes(p) || pathname.includes(p) || search.includes(p))) {
    reasons.push("Contains suspicious keywords (login / verify / account / token...)");
  }

  // 3) Multiple subdomains
  const dotCount = (hostname.match(/\./g) || []).length;
  if (dotCount > 3) reasons.push("Multiple subdomains (unusually long hostname)");

  // 4) IP address as hostname
  const ipRegex = /^(?:\d{1,3}\.){3}\d{1,3}$/;
  if (ipRegex.test(hostname)) reasons.push("Hostname is an IP address");

  // 5) '@' in URL
  if (inputUrl.includes("@")) reasons.push("Contains '@' symbol");

  // 6) Punycode / xn--
  if (hostname.includes("xn--")) reasons.push("Punycode domain (possible homograph attack)");

  // 7) URL shorteners
  const shorteners = ["bit.ly","tinyurl.com","t.co","ow.ly","buff.ly","is.gd","goo.gl","rebrand.ly","rb.gy"];
  if (shorteners.some(s => hostname === s || hostname.endsWith("." + s))) reasons.push("Shortened URL");

  // 8) Non-standard port
  if (urlObj.port && urlObj.port !== "80" && urlObj.port !== "443") reasons.push(`Uses non-standard port (${urlObj.port})`);

  // 9) Excessive path length
  if (pathname.length > 200) reasons.push("Very long path");

  // 10) Percent-encoded characters
  if (/%[0-9A-F]{2}/i.test(hostname) || /%[0-9A-F]{2}/i.test(pathname)) reasons.push("Contains percent-encoded characters");

  // 11) Suspicious query params
  const suspiciousQueryKeys = ["token","session","auth","password","passwd"];
  const urlSearchParams = new URLSearchParams(urlObj.search);
  for (const key of suspiciousQueryKeys) if (urlSearchParams.has(key)) reasons.push(`Contains query param "${key}"`);

  // 12) Very long hostname
  if (hostname.length > 60) reasons.push("Very long hostname (possible autogenerated domain)");

  const flagged = reasons.length > 0;
  return { flagged, reasons };
}

// POST endpoint
app.post(
  "/api/check-url",
  body("url").isURL({ require_protocol: true }),
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) return res.status(400).json({ errors: errors.array() });

    const { url } = req.body;
    let finalUrl = url;

    try {
      // Attempt HEAD request first
      try {
        const headResp = await axios.head(url, { maxRedirects: 5, timeout: 8000 });
        finalUrl = headResp.request?.res?.responseUrl || finalUrl;
      } catch {
        // fallback GET request
        try {
          const getResp = await axios.get(url, { maxRedirects: 5, timeout: 10000 });
          finalUrl = getResp.request?.res?.responseUrl || finalUrl;
        } catch {
          console.warn("⚠️ Could not fetch URL, using submitted URL");
          finalUrl = url;
        }
      }

      // Whitelist check
      if (isWhitelisted(finalUrl)) {
        const scan = new Scan({ submittedUrl: url, finalUrl, llmResult: null });
        await scan.save();
        return res.json({
          success: true,
          safe: true,
          finalUrl,
          reasons: ["Domain is whitelisted (trusted)"],
          llmResult: null,
        });
      }

      // Deterministic check
      const det = detectPhishing(finalUrl);
      if (det.flagged) {
        const scan = new Scan({ submittedUrl: url, finalUrl, deterministicFlags: det.reasons });
        await scan.save();
        return res.json({ success: true, safe: false, finalUrl, reasons: det.reasons, llmResult: null });
      }

      // Fetch small HTML chunk
      let htmlContent = "";
      try {
        const htmlResp = await axios.get(finalUrl, { timeout: 10000 });
        htmlContent = String(htmlResp.data).slice(0, 8000);
      } catch { /* ignore fetch errors */ }

      // LLM analysis (optional)
      let llmResult = null;
      try {
        llmResult = await analyzeWithLLM(finalUrl, htmlContent);
      } catch { /* ignore LLM errors */ }

      // Determine final safety
      let safe = true;
      const reasons = [];
      if (llmResult && llmResult.verdict) {
        const verdict = String(llmResult.verdict).toLowerCase();
        if (!verdict.includes("safe") && !verdict.includes("legit")) {
          safe = false;
          reasons.push(`LLM verdict: ${llmResult.verdict}`);
        }
      }

      const scan = new Scan({ submittedUrl: url, finalUrl, llmResult, deterministicFlags: det.reasons });
      await scan.save();

      return res.json({
        success: true,
        safe,
        finalUrl,
        reasons: det.reasons.concat(reasons),
        llmResult,
      });

    } catch (err) {
      console.error("❌ Error checking URL:", err.message || err);
      return res.status(500).json({ error: "Failed to check site safety" });
    }
  }
);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));
